# Generated by Django 5.0.6 on 2026-10-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='parsing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='parsing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('option_a', models.CharField(blank=True, default='', max_length=1000)),
                ('option_b', models.CharField(blank=True, default='', max_length=1000)),
                ('option_c', models.CharField(blank=True, default='', max_length=1000)),
                ('option_d', models.CharField(blank=True, default='', max_length=1000)),
                ('correct', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.test')),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['test', 'number'], name='exams_quest_test_id_6a0bf0_idx')],
                'unique_together': {('test', 'number')},
            },
        ),
    ]
